### ISSUE TITLE
install wrong

### ISSUE THREAD

**Issue by BASE4096** [1nhann/Autoattack#1]
error:
 File "E:\django-awd\Autoattack\autoattack\models.py", line 1, in <module>
    from utils.django_job import WebshellModel
  File "E:\django-awd\Autoattack\utils\django_job.py", line 7, in <module>
    from .webshell import Webshell
  File "E:\django-awd\Autoattack\utils\webshell.py", line 1, in <module>
    import myframework.encoder as encoder
ModuleNotFoundError: No module named 'myframework'

**Comment by 1nhann** [comment]
> 

fixed

**Comment by 1nhann** [comment]
> error: File "E:\django-awd\Autoattack\autoattack\models.py", line 1, in from utils.django_job import WebshellModel File "E:\django-awd\Autoattack\utils\django_job.py", line 7, in from .webshell import Webshell File "E:\django-awd\Autoattack\utils\webshell.py", line 1, in import myframework.encoder as encoder ModuleNotFoundError: No module named 'myframework'

Thanks for reports . Fixed .
